'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const {GameApp,SAVE_KEY}=require('../src/app');const {UNITS}=require('../src/data');
function mock(){const handlers={},storage={};const ctx=new Proxy({},{get:(o,k)=>o[k]||(()=>{}),set:(o,k,v)=>{o[k]=v;return true;}});return {handlers,storage,createCanvas:()=>({getContext:()=>ctx}),createImage:()=>({}),getWindowInfo:()=>({windowWidth:844,windowHeight:390,pixelRatio:3,safeArea:{left:35,right:809,top:0,bottom:369}}),getMenuButtonBoundingClientRect:()=>({bottom:34}),onTouchStart:f=>handlers.touch=f,onHide:f=>handlers.hide=f,onShow:f=>handlers.show=f,onWindowResize:f=>handlers.resize=f,getStorageSync:k=>storage[k],setStorageSync:(k,v)=>{storage[k]=JSON.parse(JSON.stringify(v));},removeStorageSync:k=>{delete storage[k];}};}
global.requestAnimationFrame=()=>1;
function tap(a,x,y){a.touch(a.offsetX+x*a.scale,a.offsetY+y*a.scale);}
test('mini-game project and referenced assets exist',()=>{assert.equal(JSON.parse(fs.readFileSync('project.config.json')).compileType,'game');assert.equal(JSON.parse(fs.readFileSync('game.json')).deviceOrientation,'landscape');Object.values(require('../src/art-map')).forEach(a=>assert.ok(fs.existsSync(a.path)));});
test('touch coordinates start battle and train, modal blocks underlying controls',()=>{const a=new GameApp(mock());a.renderer.draw();tap(a,150,550);assert.equal(a.scene,'battle');a.renderer.draw();tap(a,155,650);assert.equal(a.battle.sides[0].queue.length,1);tap(a,50,650);a.renderer.draw();assert.ok(a.modal.unit);const count=a.battle.sides[0].queue.length;tap(a,155,650);assert.equal(a.battle.sides[0].queue.length,count);});
test('background persists, restore starts paused and rendering covers every era and modal',()=>{const w=mock(),a=new GameApp(w);a.startBattle();a.battle.tick();w.handlers.hide();assert.ok(a.paused);assert.ok(w.storage[SAVE_KEY]);w.handlers.show();assert.ok(a.paused);const restored=new GameApp(w);restored.resume();assert.equal(restored.battle.time,a.battle.time);assert.ok(restored.paused);a.paused=false;for(let era=0;era<5;era++){a.battle.sides[0].era=era;for(const page of [0,1]){a.page=page;a.renderer.draw();}a.modal='defense';a.renderer.draw();for(const unit of UNITS.filter(u=>u.era===era)){a.modal={unit:unit.id};a.renderer.draw();}}a.modal='help';a.renderer.draw();a.paused=true;a.renderer.draw();a.modal=null;a.battle.command(0,{type:'surrender'});a.renderer.draw();});
test('pause and hidden state stop simulation; storage errors do not stop game',()=>{const w=mock();w.setStorageSync=()=>{throw new Error('quota');};const a=new GameApp(w);a.startBattle();assert.ok(a.saveUnavailable);a.frame(1000);a.frame(1100);const time=a.battle.time;a.paused=true;a.frame(1200);assert.equal(a.battle.time,time);a.hidden=true;a.frame(1300);assert.equal(a.battle.time,time);});
