'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {Battle,STEP}=require('../src/battle');const {UNITS,BY_ID,ERAS}=require('../src/data');
function run(b,seconds,ai=false){for(let i=0;i<Math.ceil(seconds/STEP);i++)b.tick(STEP,ai);}
test('five complete eras and 30 distinct configurations',()=>{assert.equal(new Set(UNITS.map(u=>u.id)).size,30);ERAS.forEach((_,era)=>assert.equal(UNITS.filter(u=>u.era===era).length,6));});
test('failed commands do not charge or reserve population',()=>{const b=new Battle();b.sides[0].gold=0;const before=b.snapshot();assert.equal(b.command(0,{type:'train',id:'age1_melee'}),'金币不足');assert.deepEqual(b.snapshot(),before);assert.ok(b.command(0,{type:'train',id:'age2_melee'}));});
test('queue limit, reservations and refunds',()=>{const b=new Battle(),s=b.sides[0];s.gold=1000;for(let i=0;i<5;i++)assert.equal(b.command(0,{type:'train',id:'age1_melee'}),null);assert.equal(b.population(0),5);assert.equal(b.command(0,{type:'train',id:'age1_melee'}),'生产队列已满');assert.equal(s.gold,650);b.command(0,{type:'cancel',id:s.queue[1].id});assert.equal(s.gold,720);b.command(0,{type:'cancel',id:s.queue[0].id});assert.equal(s.gold,772);run(b,2.1);assert.equal(b.population(0),3);assert.equal(b.units.length,1);});
test('population rejects overbooking',()=>{const b=new Battle();b.sides[0].gold=1000;for(let i=0;i<10;i++)b.spawn(0,'age1_heavy');assert.equal(b.command(0,{type:'train',id:'age1_melee'}),'人口已满');assert.equal(b.sides[0].gold,1000);});
test('evolution retains paid old queue, old towers, cooldown and base HP',()=>{const b=new Battle(),s=b.sides[0];s.gold=1000;b.command(0,{type:'train',id:'age1_melee'});b.command(0,{type:'build',slot:0,kind:0});s.xp=300;s.hp=2000;s.cooldown=31;assert.equal(b.command(0,{type:'evolve'}),null);assert.equal(s.queue[0].typeId,'age1_melee');assert.equal(s.towers[0].era,0);assert.equal(s.cooldown,31);assert.equal(s.hp,2000);assert.ok(b.command(0,{type:'train',id:'age1_melee'}));run(b,2.1);assert.equal(b.units[0].typeId,'age1_melee');});
test('armor relationships apply across eras',()=>{const b=new Battle();assert.ok(b.damage(BY_ID.age1_spear,'heavy')>b.damage(BY_ID.age1_spear,'light'));const a=b.spawn(0,'age1_spear'),z=b.spawn(1,'age5_heavy');a.x=490;z.x=520;z.clock=9;const shield=z.shield;run(b,STEP);assert.ok(z.shield<shield);});
test('dead support recipient cannot resurrect and death reward is unique',()=>{const b=new Battle(),victim=b.spawn(0,'age1_melee'),medic=b.spawn(0,'age2_support'),enemy=b.spawn(1,'age1_heavy');victim.x=500;victim.hp=1;victim.clock=9;medic.x=460;enemy.x=510;b.tick(STEP,false);assert.ok(!b.units.includes(victim));assert.equal(b.sides[1].kills,1);b.tick(STEP,false);assert.equal(b.sides[1].kills,1);});
test('healing tags exclude machinery; repair includes older machinery',()=>{const b=new Battle(),medic=b.spawn(0,'age2_support'),machine=b.spawn(0,'age2_ballista');medic.x=200;machine.x=230;machine.hp=10;b.tick(STEP,false);assert.equal(machine.hp,10);const repair=b.spawn(0,'age5_support');repair.x=220;b.tick(STEP,false);assert.ok(machine.hp>10);});
test('both bases destroyed in same step is a draw and settlement is immutable',()=>{const b=new Battle();const a=b.spawn(0,'age1_melee'),z=b.spawn(1,'age1_melee');a.x=1000;z.x=0;b.sides.forEach(s=>s.hp=1);b.tick(STEP,false);assert.equal(b.result.winner,null);assert.equal(b.result.reason,'双方基地同时摧毁');const result=b.snapshot();b.tick();assert.ok(b.command(0,{type:'surrender'}));assert.deepEqual(b.snapshot(),result);});
test('skill warns, preserves cast era and does not damage bases or allies',()=>{const b=new Battle(),p=b.sides[0];p.cooldown=0;const target=b.spawn(1,'age1_melee'),friend=b.spawn(0,'age1_melee');target.x=500;friend.x=800;target.clock=99;friend.clock=99;assert.ok(b.command(0,{type:'skill',x:-1}));assert.equal(p.cooldown,0);b.command(0,{type:'skill',x:500});p.xp=300;b.command(0,{type:'evolve'});assert.equal(b.strikes[0].era,0);run(b,0.5);assert.equal(target.hp,BY_ID.age1_melee.hp);run(b,0.6);assert.ok(target.hp<BY_ID.age1_melee.hp);assert.equal(friend.hp,BY_ID.age1_melee.hp);assert.equal(b.sides[1].hp,3000);});
test('tower purchase upgrade and sale account for actual paid cost',()=>{const b=new Battle(),s=b.sides[0];s.gold=1000;b.command(0,{type:'build',slot:0,kind:0});b.command(0,{type:'upgrade',slot:0});assert.equal(s.gold,712);assert.ok(b.command(0,{type:'upgrade',slot:0}));b.command(0,{type:'sell',slot:0});assert.equal(s.gold,856);});
test('20 minute time limit compares base HP',()=>{const b=new Battle();b.time=1200-STEP;b.sides[0].hp=2900;b.tick(STEP,false);assert.equal(b.result.winner,1);});
test('snapshot restore produces deterministic future combat',()=>{const a=new Battle({seed:42});a.command(0,{type:'train',id:'age1_heavy'});run(a,30,true);const b=Battle.restore(a.snapshot());assert.ok(b);run(a,30,true);run(b,30,true);assert.deepEqual(a.snapshot(),b.snapshot());assert.equal(Battle.restore({version:'old'}),null);});
test('full-length AI simulations preserve economy, queue and population bounds',()=>{for(const difficulty of ['easy','normal','hard']){const b=new Battle({difficulty,seed:200});for(let i=0;i<36000&&!b.result;i++){if(i%60===0){const s=b.sides[0];b.command(0,{type:'evolve'});const roster=UNITS.filter(u=>u.era===s.era&&!u.support);b.command(0,{type:'train',id:roster[(i/60)%roster.length].id});}b.tick();for(let side=0;side<2;side++){assert.ok(b.sides[side].gold>=0);assert.ok(b.population(side)<=30);assert.ok(b.sides[side].queue.length<=5);}}assert.ok(b.result);}});

test('malformed or oversized snapshots are rejected without crashing',()=>{
  const b=new Battle();b.command(0,{type:'train',id:'age1_melee'});
  for(const mutate of [s=>s.sides[0].queue[0].remaining=null,s=>s.units.push(null),s=>s.strikes.push({}),s=>s.sides[0].towers[0]={},s=>s.sides[0].slots=99,s=>s.nextId=1]){const snapshot=b.snapshot();mutate(snapshot);assert.equal(Battle.restore(snapshot),null);}
  const raw=b.snapshot(),restored=Battle.restore(raw);raw.sides[0].gold=99999;assert.notEqual(restored.sides[0].gold,99999);
});

test('shield infantry does not reduce a single-victim area blast',()=>{
 const b=new Battle(),shield=b.spawn(0,'age2_melee'),fire=b.spawn(1,'age1_fire');shield.x=500;shield.clock=99;fire.x=620;
 b.tick(STEP,false);assert.equal(BY_ID.age2_melee.hp-shield.hp,b.damage(BY_ID.age1_fire,'light'));
});
